version: "3"
services:
  cache:
    image: nginx
    build: .
    ports:
      - "8080:80"
    links:
      - static
    depends_on:
      - static
  static:
    image: nginx
    volumes:
      - ~/Videos:/usr/share/nginx/html
  redis:
    image: redis:latest
volumes:
  logvolume01: {}
