version: "3"
services:
  cache:
    image: nginx
    ports:
      - "8080:80"
    links:
      - static
    depends_on:
      - static
    volumes: 
      - ./cache_nginx.conf:/etc/nginx/nginx.conf
      - ./cache:/home/nginx/proxy_cache/cache
  static:
    image: nginx
    # ports: 
    #   - "8081:80"
    volumes:
      - ~/Videos:/usr/share/nginx/html
  redis:
    image: redis:latest
volumes:
  logvolume01: {}
