version: '3'
services:
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    # build:
    #   context: ./images/influxdb/
    #   dockerfile: ./${TYPE}/Dockerfile
    #   args:
    #     INFLUXDB_TAG: ${INFLUXDB_TAG}
    image: "influxdb"
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8088:8088"
      # UDP Port
      - "8089:8089/udp"
    environment:
      INFLUXDB_HTTP_FLUX_ENABLED: "true"
      INFLUXDB_HTTP_FLUX_LOG_ENABLED: "true"
      INFLUXDB_ADMIN_ENABLED: "true"

  telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    # build:
    #   context: ./images/telegraf/
    #   dockerfile: ./${TYPE}/Dockerfile
    #   args:
    #     TELEGRAF_TAG: ${TELEGRAF_TAG}
    image: "telegraf"
    environment:
      HOSTNAME: "telegraf-getting-started"
    # Telegraf requires network access to InfluxDB
    links:
      - influxdb
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb

  chronograf:
    # Full tag list: https://hub.docker.com/r/library/chronograf/tags/
    # build:
    #   context: ./images/chronograf
    #   dockerfile: ./${TYPE}/Dockerfile
    #   args:
    #     CHRONOGRAF_TAG: ${CHRONOGRAF_TAG}
    image: "chronograf"
    environment:
      RESOURCES_PATH: "/usr/share/chronograf/resources"
    volumes:
      # Mount for chronograf database
      - ./chronograf/data/:/var/lib/chronograf/
    links:
      # Chronograf requires network access to InfluxDB and Kapacitor
      - influxdb
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb
      - telegraf
