version: "3"
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "${NGINX_PORT:-8081}:80"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /home/ubuntu/Work/video-hls:/usr/share/nginx/html
      - /home/ubuntu/Work/video-hls/nginx.conf:/etc/nginx/conf.d/default.conf
