version: "3"
services:
  cache:
    restart: always
    image: nginx
    ports:
      - "8080:80"
    links:
      - static
    depends_on:
      - static
    volumes: 
      - ./conf/backend.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxycache:/home/nginx/proxy_cache/cache
      - ./cache_access.log:/var/log/nginx/access.log
  static:
    restart: always
    image: nginx
    volumes:
      - ~/Videos:/usr/share/nginx/html
      - ./static_access.log:/var/log/nginx/access.log
volumes:
  logvolume01: {}
