[template]
src = "services.conf.tmpl"
dest = "/etc/nginx/conf.d/default.conf"
keys = [
  "/services/web"
]
check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd  = "/usr/sbin/service nginx reload"