version: "3"
services:
  test_lua:
    restart: always
    image: openresty/openresty
    ports:
      - "8087:80"
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf
volumes:
  logvolume01: {}
