version: "3"
services:
  cache:
    image: nginx
    ports:
      - "8080:80"
    links:
      - static
    depends_on:
      - static
    volumes: 
      - ../conf:/etc/nginx/conf.d/
  static:
    image: nginx
    # ports: 
    #   - "8081:80"
    volumes:
      - ~/Videos:/usr/share/nginx/html
volumes:
  logvolume01: {}
